### ISSUE TITLE
Minor issue with f-string in `CriresPipeline.save_extracted_data`

### ISSUE THREAD

**Issue by DGonzalezPicos** [yapenzhang/excalibuhr#2]
### Describe the issue:
The function `CriresPipeline.save_extracted_data` runs into a TypeError at  line 2029 when trying to print the average S/N of the extracted spectrum as an f-string `{snr_mid:.2f}`.

### Error message
`TypeError: unsupported format string passed to numpy.ndarray.__format__`

### Context for the issue
In my situation the variable `snr_mid` is an array with two elements e.g. [132.23845688 143.72093372], can be fixed by simply taking the mean or 
`snr_mid = np.mean((spec_series/err_series)[:,wlens.shape[0]//2,:])`
 instead of 
`snr_mid = np.mean((spec_series/err_series)[:,wlens.shape[0]//2,:], axis=1)`

My `spec_series` have shape (2,21,2048), is that the expected behavior or the source of the error?

### Runtime information
Python 3.11.5 
excalibuhr-0.1 | installed from source (git)

**Comment by yapenzhang** [comment]
Thanks for catching the bug! I just changed the format of printing to print array properly. This should now print the SNR of each frame (in the case of time series observations).
In your case, the `spec_series` has a length of 2, which means you set `combine=False` and kept the spectra of nodding position A and B separately, right? You may also simply set `combine=True` to obtain a final combined spectrum. Let me know if that fix the issue.

**Comment by DGonzalezPicos** [comment]
Yes that works, thanks!
